
data.path.base=./data

# JSON ?????
data.path.actors.json=./data/actors.json
data.path.movies.json=./data/movies.json
data.path.screenings.json=./data/screenings.json
data.path.halls.json=./data/halls.json
data.path.tickets.json=./data/tickets.json

# YAML ?????
data.path.actors.yaml=./data/actors.yaml
data.path.movies.yaml=./data/movies.yaml
data.path.screenings.yaml=./data/screenings.yaml
data.path.halls.yaml=./data/halls.yaml
data.path.tickets.yaml=./data/tickets.yaml
