data.path.base=./data

data.path.actors.json=actors.json
data.path.movies.json=movies.json
data.path.screenings.json=screenings.json
data.path.halls.json=halls.json
data.path.tickets.json=tickets.json

data.path.actors.yaml=actors.yaml
data.path.movies.yaml=movies.yaml
data.path.screenings.yaml=screenings.yaml
data.path.halls.yaml=halls.yaml
data.path.tickets.yaml=tickets.yaml

